# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jungslee <jungslee@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/23 17:15:27 by jungslee          #+#    #+#              #
#    Updated: 2024/03/14 19:01:46 by jungslee         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	cc -L./mlx -lmlx -framework OpenGL -framework Appkit map_validity.c map_init.c main.c error.c -g